/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package songschords;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author qwer
 */
public class SongEditorFrame extends javax.swing.JFrame {

    private MainFrame parentFrame = null;
    private final String defaultTitle = "Edit Song";
    
    private String author = "", title = "";
    private boolean edit = false;
    
    /**
     * Creates new form NewSongFrame
     * @param parentFrame
     */
    public SongEditorFrame(MainFrame parentFrame) {
        initComponents();

        try {
            setIconImage(ImageIO.read(getClass().getResourceAsStream("/images/guitar.png")));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.parentFrame = parentFrame;

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    public void newSong() {
        updateAuthorsBox("");
        updateTitlesBox("", "");

        author = title = "";
        this.edit = false;
        
        authorsBox.getEditor().setItem("");
        titlesBox.getEditor().setItem("");
        
        songTextArea.setText("");
        
        setTitle("Edit Song");

        
        setVisible(true);
    }
        
    public void show(String author, String title, boolean edit) {
        updateAuthorsBox(author);
        updateTitlesBox(author, title);

        this.author = author;
        this.title = title;
        this.edit = edit;
        
        authorsBox.setSelectedItem(author);

        songTextArea.setText(SongsProcessor.getSongs().get(author).get(title)[1]);
        
        setTitle("Edit Song | " + author + " : " + title);
        
        
        setVisible(true);
    }
    
    public void updateAuthorsBox(String selectedAuthor) {
        Set<String> authorsSet = SongsProcessor.getAuthorsSet();
        
        authorsBox.removeAllItems();
        
        for (String author : authorsSet) {
            authorsBox.addItem(author);
        }
        
        authorsBox.setSelectedItem(selectedAuthor);
    }

    public void updateTitlesBox(String selectedAuthor, String selectedTitle) {
        Set<String> titlesSet = SongsProcessor.getAuthorTitlesSet(selectedAuthor);
        
        titlesBox.removeAllItems();
        
        for (String title : titlesSet) {
            titlesBox.addItem(title);
        }
        
        titlesBox.setSelectedItem(selectedTitle);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        songTextArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        authorsBox = new javax.swing.JComboBox();
        titlesBox = new javax.swing.JComboBox();

        setTitle("Edit Song");

        jLabel1.setText("Author:");

        jLabel2.setText("Title:");

        jLabel3.setText("Text:");

        songTextArea.setColumns(20);
        songTextArea.setRows(5);
        jScrollPane1.setViewportView(songTextArea);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        authorsBox.setEditable(true);

        titlesBox.setEditable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 177, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)
                        .addGap(12, 12, 12)
                        .addComponent(helpButton))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorsBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titlesBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(authorsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titlesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton)
                    .addComponent(helpButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String newAuthor = authorsBox.getSelectedItem().toString().trim();
        String newTitle = titlesBox.getSelectedItem().toString().trim();
        String song = songTextArea.getText().trim();
        
        SongResult result = null;
        
        if (edit) {
            result = SongsProcessor.editSong(SongsProcessor.getFilenameByAuthorAndTitle(author, title), newAuthor, newTitle, song);
        } else if (SongsProcessor.exists(newAuthor, newTitle)) {
            if (JOptionPane.showConfirmDialog(this, "Song with title\"" + newTitle + "\" already exists. Overwrite?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                result = SongsProcessor.editSong(SongsProcessor.getFilenameByAuthorAndTitle(author, title), newAuthor, newTitle, song);
            }
        } else {
            result = SongsProcessor.editSong("", newAuthor, newTitle, song);
        }
        
        if (result != null) {
            if (result.status) {
                parentFrame.updateSongsTree();
                JOptionPane.showMessageDialog(this, "Song saved success", "Save", JOptionPane.INFORMATION_MESSAGE);
                author = newAuthor;
                title = newTitle;
                edit = true;
                setTitle(defaultTitle + " | " + author + " - " + title);
            } else {
                JOptionPane.showMessageDialog(this, result.message, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Cancel changes?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            setVisible(false);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        MainFrame.helpFrame.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox authorsBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea songTextArea;
    private javax.swing.JComboBox titlesBox;
    // End of variables declaration//GEN-END:variables
}
